[package]
name = "centered-windows"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
pollster = "0.3.0"
wgpu = "22.1.0"
winit = "0.30.5"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.58.0"
features = [
	"Win32_UI_WindowsAndMessaging",
]
